---

- name: installing zk from apt
  apt: name={{ item  }} state=present update_cache=yes
  with_items:
    - zookeeper
    - zookeeperd

- name: setting zoo.id
  template: src=zoo_id.j2 dest=/etc/zookeeper/conf/myid

- name: transfering zoo.cfg
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg

- name: restarting ZK
  service: name=zookeeper state=restarted

#- name: Installation of Zookeeper Binaries
#  apt: name={{ item  }} state=present update_cache=yes
#  with_items:
#    - zookeeper
#    - zookeeperd
#    - maven
#
#- name: Preparing directories
#  shell: mkdir -p {{ zk_home }}/{}
#  with_items:
#    - {{ zk_home }}
#    - {{ zk_datadir }}
#    - {{ exhibitor_home }}
#
#- name: Downloading ZooKeeper
#  shell: wget http://www.eu.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
#
#- shell: tar -xzvf zookeeper-3.4.6.tar.gz -C {{ zk_home }} --strip-components=1
#
#- name: Delete zookeeper configuration if present
#  file: path={{ item }} state=absent
#  with_items:
#    - {{ zk_home }}/conf/zoo.cfg
#    - {{ zk_datadir }}/data/myid
#
#- name: ZooKeeper ID configuration
#  template: src=zoo_id.j2 dest={{ zk_datadir }}/myid
#
#- name: ZooKeeper Config file
#  template: src=zoo.cfg.j2 dest={{ zk_home }}/conf/zoo.cfg
#
#- name: Download Exhibitor pom
#  get_url:
#    url=https://raw.github.com/Netflix/exhibitor/master/exhibitor-standalone/src/main/resources/buildscripts/standalone/maven/pom.xml
#    dest={{ exhibitor_home }}
#
#- name: Build Exhibitor
#  shell: "mvn assembly:single"
#  args:
#    chdir: {{ exhibitor_home }}
#
#- name: Prepare launch script
#  shell: echo 'java -jar {{ exhibitor_home }}/target/exhibitor-1.0-jar-with-dependencies.jar -c file --hostname {{ ansible_eth1.ipv4.address }}' > /etc/exhibitor/start.sh
#
#- shell: chmod +x {{ exhibitor_home }}/start.sh
#
#- name: Launch ZooKeeper
#  action: shell nohup {{ zk_home }}/bin/zkServer.sh start
#  async: 1000000
#  poll: 0
#
#- name: Launch Exhibitor
#  action: shell nohup {{ exhibitor_home }}/start.sh
#  async: 1000000
#  poll: 0