- name: installing mesos package
  apt: name=mesos state=present update_cache=yes

- name: stopping running services
  service: name={{ item }} state=stopped
  with_items:
    - mesos-master
    - mesos-slave

- name: setting ZK ensemble address
  template: src=zk.j2 dest=/etc/mesos/zk

- name: setting cluster name
  shell: echo {{ clusterName }} > /etc/mesos-master/cluster

- name: setting qourum
  shell: echo {{ quorum }} > /etc/mesos-master/quorum

- name: starting master nodes
  service: name={{ item }} state=started
  when: mesos_install_mode == 'mixed'
  with_items:
    - mesos-master
    - mesos-slave

#Starting Masters-only
- name: starting master nodes
  service: name=mesos-master state=started
  when: mesos_install_mode == 'master'

- name: overriding slaves start up configuration
  shell: echo manual > /etc/init/mesos-slave.override
  when: mesos_install_mode == 'master'

#Starting Slave-only nodes
- name: starting slave nodes
  service: name=mesos-slave state=started
  when: mesos_install_mode == 'slave'

- name: overriding master start up configuration
  shell: echo manual > /etc/init/mesos-master.override
  when: mesos_install_mode == 'slave'